version: "3.9"
services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    volumes:
      - ./init_db/data/yellow_tripdata_2020-01.csv:/init_db/data/yellow_tripdata_2020-01.csv
    ports:
      - 5432:5432
    networks:
      - project-network
    environment:
      POSTGRES_DB: taxi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: taxiuser
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always

  app:
    container_name: python
    build: ./app/
    volumes:
      - ./app/src/config.py:/app/config.py
      - ./app/src/raw.py:/app/raw.py
      - ./app/src/core.py:/app/core.py
    command: sh -c "python raw.py && python core.py"
    ports:
      - 4000:4000
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      - project-network
 
networks:
  project-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16 # Подсеть для контейнеров
